'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 2.0.50727.42.
'
Namespace localhost
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SpringWSSoapBinding", [Namespace]:="https://pgtest.sarmayebank.com/axis/SpringWS")>  _
    Partial Public Class SpringWSEndPointService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private paymentGatewayVoidRequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private paymentGatewayVerificationRequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private paymentGatewayReconciliationRequestOperationCompleted As System.Threading.SendOrPostCallback
        
        Private paymentGatewayMerchantAuthenticationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private paymentGatewayLinksAuthenticationOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.Portal.My.MySettings.Default.Portal_localhost_SpringWSEndPointService
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event paymentGatewayVoidRequestCompleted As paymentGatewayVoidRequestCompletedEventHandler
        
        '''<remarks/>
        Public Event paymentGatewayVerificationRequestCompleted As paymentGatewayVerificationRequestCompletedEventHandler
        
        '''<remarks/>
        Public Event paymentGatewayReconciliationRequestCompleted As paymentGatewayReconciliationRequestCompletedEventHandler
        
        '''<remarks/>
        Public Event paymentGatewayMerchantAuthenticationCompleted As paymentGatewayMerchantAuthenticationCompletedEventHandler
        
        '''<remarks/>
        Public Event paymentGatewayLinksAuthenticationCompleted As paymentGatewayLinksAuthenticationCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://webservice.ambit.avanza.com", ResponseNamespace:="https://pgtest.sarmayebank.com/axis/SpringWS")>  _
        Public Function paymentGatewayVoidRequest(ByVal RRN As String, ByVal reservationNum As String, ByVal userName As String, ByVal password As String, ByVal url As String, ByVal amount As String) As <System.Xml.Serialization.SoapElementAttribute("paymentGatewayVoidRequestReturn")> String
            Dim results() As Object = Me.Invoke("paymentGatewayVoidRequest", New Object() {RRN, reservationNum, userName, password, url, amount})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub paymentGatewayVoidRequestAsync(ByVal RRN As String, ByVal reservationNum As String, ByVal userName As String, ByVal password As String, ByVal url As String, ByVal amount As String)
            Me.paymentGatewayVoidRequestAsync(RRN, reservationNum, userName, password, url, amount, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub paymentGatewayVoidRequestAsync(ByVal RRN As String, ByVal reservationNum As String, ByVal userName As String, ByVal password As String, ByVal url As String, ByVal amount As String, ByVal userState As Object)
            If (Me.paymentGatewayVoidRequestOperationCompleted Is Nothing) Then
                Me.paymentGatewayVoidRequestOperationCompleted = AddressOf Me.OnpaymentGatewayVoidRequestOperationCompleted
            End If
            Me.InvokeAsync("paymentGatewayVoidRequest", New Object() {RRN, reservationNum, userName, password, url, amount}, Me.paymentGatewayVoidRequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnpaymentGatewayVoidRequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.paymentGatewayVoidRequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent paymentGatewayVoidRequestCompleted(Me, New paymentGatewayVoidRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://webservice.ambit.avanza.com", ResponseNamespace:="https://pgtest.sarmayebank.com/axis/SpringWS")>  _
        Public Function paymentGatewayVerificationRequest(ByVal purchaseRRN As String, ByVal purchaseStan As String, ByVal reservationNum As String, ByVal userName As String, ByVal password As String, ByVal url As String) As <System.Xml.Serialization.SoapElementAttribute("paymentGatewayVerificationRequestReturn")> String
            Dim results() As Object = Me.Invoke("paymentGatewayVerificationRequest", New Object() {purchaseRRN, purchaseStan, reservationNum, userName, password, url})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub paymentGatewayVerificationRequestAsync(ByVal purchaseRRN As String, ByVal purchaseStan As String, ByVal reservationNum As String, ByVal userName As String, ByVal password As String, ByVal url As String)
            Me.paymentGatewayVerificationRequestAsync(purchaseRRN, purchaseStan, reservationNum, userName, password, url, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub paymentGatewayVerificationRequestAsync(ByVal purchaseRRN As String, ByVal purchaseStan As String, ByVal reservationNum As String, ByVal userName As String, ByVal password As String, ByVal url As String, ByVal userState As Object)
            If (Me.paymentGatewayVerificationRequestOperationCompleted Is Nothing) Then
                Me.paymentGatewayVerificationRequestOperationCompleted = AddressOf Me.OnpaymentGatewayVerificationRequestOperationCompleted
            End If
            Me.InvokeAsync("paymentGatewayVerificationRequest", New Object() {purchaseRRN, purchaseStan, reservationNum, userName, password, url}, Me.paymentGatewayVerificationRequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnpaymentGatewayVerificationRequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.paymentGatewayVerificationRequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent paymentGatewayVerificationRequestCompleted(Me, New paymentGatewayVerificationRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://webservice.ambit.avanza.com", ResponseNamespace:="https://pgtest.sarmayebank.com/axis/SpringWS")>  _
        Public Function paymentGatewayReconciliationRequest(ByVal userName As String, ByVal password As String, ByVal url As String) As <System.Xml.Serialization.SoapElementAttribute("paymentGatewayReconciliationRequestReturn")> String
            Dim results() As Object = Me.Invoke("paymentGatewayReconciliationRequest", New Object() {userName, password, url})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub paymentGatewayReconciliationRequestAsync(ByVal userName As String, ByVal password As String, ByVal url As String)
            Me.paymentGatewayReconciliationRequestAsync(userName, password, url, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub paymentGatewayReconciliationRequestAsync(ByVal userName As String, ByVal password As String, ByVal url As String, ByVal userState As Object)
            If (Me.paymentGatewayReconciliationRequestOperationCompleted Is Nothing) Then
                Me.paymentGatewayReconciliationRequestOperationCompleted = AddressOf Me.OnpaymentGatewayReconciliationRequestOperationCompleted
            End If
            Me.InvokeAsync("paymentGatewayReconciliationRequest", New Object() {userName, password, url}, Me.paymentGatewayReconciliationRequestOperationCompleted, userState)
        End Sub
        
        Private Sub OnpaymentGatewayReconciliationRequestOperationCompleted(ByVal arg As Object)
            If (Not (Me.paymentGatewayReconciliationRequestCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent paymentGatewayReconciliationRequestCompleted(Me, New paymentGatewayReconciliationRequestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://webservice.ambit.avanza.com", ResponseNamespace:="https://pgtest.sarmayebank.com/axis/SpringWS")>  _
        Public Function paymentGatewayMerchantAuthentication(ByVal reservationNum As String, ByVal userName As String, ByVal password As String, ByVal url As String, ByVal amount As String) As <System.Xml.Serialization.SoapElementAttribute("paymentGatewayMerchantAuthenticationReturn")> String
            Dim results() As Object = Me.Invoke("paymentGatewayMerchantAuthentication", New Object() {reservationNum, userName, password, url, amount})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub paymentGatewayMerchantAuthenticationAsync(ByVal reservationNum As String, ByVal userName As String, ByVal password As String, ByVal url As String, ByVal amount As String)
            Me.paymentGatewayMerchantAuthenticationAsync(reservationNum, userName, password, url, amount, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub paymentGatewayMerchantAuthenticationAsync(ByVal reservationNum As String, ByVal userName As String, ByVal password As String, ByVal url As String, ByVal amount As String, ByVal userState As Object)
            If (Me.paymentGatewayMerchantAuthenticationOperationCompleted Is Nothing) Then
                Me.paymentGatewayMerchantAuthenticationOperationCompleted = AddressOf Me.OnpaymentGatewayMerchantAuthenticationOperationCompleted
            End If
            Me.InvokeAsync("paymentGatewayMerchantAuthentication", New Object() {reservationNum, userName, password, url, amount}, Me.paymentGatewayMerchantAuthenticationOperationCompleted, userState)
        End Sub
        
        Private Sub OnpaymentGatewayMerchantAuthenticationOperationCompleted(ByVal arg As Object)
            If (Not (Me.paymentGatewayMerchantAuthenticationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent paymentGatewayMerchantAuthenticationCompleted(Me, New paymentGatewayMerchantAuthenticationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace:="http://webservice.ambit.avanza.com", ResponseNamespace:="https://pgtest.sarmayebank.com/axis/SpringWS")>  _
        Public Function paymentGatewayLinksAuthentication(ByVal userName As String, ByVal password As String, ByVal url As String) As <System.Xml.Serialization.SoapElementAttribute("paymentGatewayLinksAuthenticationReturn")> String
            Dim results() As Object = Me.Invoke("paymentGatewayLinksAuthentication", New Object() {userName, password, url})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub paymentGatewayLinksAuthenticationAsync(ByVal userName As String, ByVal password As String, ByVal url As String)
            Me.paymentGatewayLinksAuthenticationAsync(userName, password, url, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub paymentGatewayLinksAuthenticationAsync(ByVal userName As String, ByVal password As String, ByVal url As String, ByVal userState As Object)
            If (Me.paymentGatewayLinksAuthenticationOperationCompleted Is Nothing) Then
                Me.paymentGatewayLinksAuthenticationOperationCompleted = AddressOf Me.OnpaymentGatewayLinksAuthenticationOperationCompleted
            End If
            Me.InvokeAsync("paymentGatewayLinksAuthentication", New Object() {userName, password, url}, Me.paymentGatewayLinksAuthenticationOperationCompleted, userState)
        End Sub
        
        Private Sub OnpaymentGatewayLinksAuthenticationOperationCompleted(ByVal arg As Object)
            If (Not (Me.paymentGatewayLinksAuthenticationCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent paymentGatewayLinksAuthenticationCompleted(Me, New paymentGatewayLinksAuthenticationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub paymentGatewayVoidRequestCompletedEventHandler(ByVal sender As Object, ByVal e As paymentGatewayVoidRequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class paymentGatewayVoidRequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub paymentGatewayVerificationRequestCompletedEventHandler(ByVal sender As Object, ByVal e As paymentGatewayVerificationRequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class paymentGatewayVerificationRequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub paymentGatewayReconciliationRequestCompletedEventHandler(ByVal sender As Object, ByVal e As paymentGatewayReconciliationRequestCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class paymentGatewayReconciliationRequestCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub paymentGatewayMerchantAuthenticationCompletedEventHandler(ByVal sender As Object, ByVal e As paymentGatewayMerchantAuthenticationCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class paymentGatewayMerchantAuthenticationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42")>  _
    Public Delegate Sub paymentGatewayLinksAuthenticationCompletedEventHandler(ByVal sender As Object, ByVal e As paymentGatewayLinksAuthenticationCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class paymentGatewayLinksAuthenticationCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
End Namespace
